determining executable activities
Noel-Bastubbe/for-Construction-Modeling pull request #163
Opened 2023-05-10 10:03 UTC by Noel-Bastubbe

Description: 
- adds the required data types to determine executable activities
- adds the ability to determine executable activities
- adds tests to determining executable activities

## PR checklist

- [ ] dev-branch has been merged into local branch to resolve conflicts
- [ ] the application has been manually tested after merge
- [ ] another dev reviewed and approved
- [ ] if feature-Branch: Teams PO has approved (show via e.g. screenshots/screencapture/live demo)

2023-05-10 11:43 UTC, AnjoSs requested changes, later dismissed
Looks great! I left some comments regarding the naming of your classes. I hope my suggestions make it a bit clearer. Maybe you have even better ideas.

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +    public constructor(name: string, duration: number, NoP: number, role: Role, input: IOSet[], output: IOSet[]) {
You could already add default values for the duration (1) and the NoP (1) and maybe null for the role.

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +export class ProjectState {
```suggestion
export class ExecutionState {
```

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +export class Instance {
```suggestion
export class DataObject {
```

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +export class Instance {
```suggestion
export class DataObject {
```

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +export class State {
You could call it `DataObjectNode` with the attributes `class`, `state`, and `isList` to make sure it maps to the nodes in the fragments.

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +    public satisfiedBy(currentState: State[]): boolean {
This should be the execution state I guess

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +                    satisfiedBy = false;
```suggestion
                    return false;
```

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +        return satisfiedBy;
```suggestion
        return true;
```

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +        this.set.forEach(function (State) {
```suggestion
        this.set.forEach(function (dataObjectNode) {
```

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +    set: Array<{ dataObject: State, isList: boolean }>;
Use DataObjectNodes here instead

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +    public isExecutable(currentState: State[], ressources: Resource[]): boolean {
```suggestion
    public isExecutable(currentState: ExecutionState[], ressources: Resource[]): boolean {
```

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +    output: IOSet[];
```suggestion
    inputSets: IOSet[];
    outputSets: IOSet[];
```

2023-05-10 11:43 UTC, AnjoSs commented on planner/types.ts
> +export class Activity {
Or at least group the classes into something like activity and IOsets, data object-related stuff, and execution state, and objectives.

2023-05-15 09:27 UTC, Firsttryy approved these changes
LGTM

2023-05-15 09:29 UTC, Firsttryy approved these changes
LGTM

2023-05-15 10:45 UTC, simonmichaelnowack approved these changes

2023-05-15 10:49 UTC, merged