Feature/167 ps add button
Noel-Bastubbe/for-Construction-Modeling pull request #176
Opened 2023-05-15 13:21 UTC by rebekka0111

Fixes #167 

Adds a generate plan button, which opens a test dialog with the message "This is not possible right now." 

## PR checklist

- [ ] dev-branch has been merged into local branch to resolve conflicts
- [ ] the application has been manually tested after merge
- [ ] another dev reviewed and approved
- [ ] if feature-Branch: Teams PO has approved (show via e.g. screenshots/screencapture/live demo)

2023-05-15 13:38 UTC, Firsttryy approved these changes
LGTM

2023-05-16 07:52 UTC, Firsttryy approved these changes

2023-05-16 08:23 UTC, Noel-Bastubbe requested changes

2023-05-16 08:23 UTC, Noel-Bastubbe commented on app/index.html
> +    <div id="placeholder" class="errorBarControls">
Please change the id to a more meaningful discription than "placeholder"

2023-05-16 10:55 UTC, Noel-Bastubbe approved these changes

2023-05-16 10:57 UTC, merged