Wiki links
Noel-Bastubbe/for-Construction-Modeling pull request #227
Opened 2023-06-02 18:02 UTC by libaumann

Wiki links are now updated 

## PR checklist

- [ ] dev-branch has been merged into local branch to resolve conflicts
- [ ] the application has been manually tested after merge
- [ ] another dev reviewed and approved
- [ ] if feature-Branch: Teams PO has approved (show via e.g. screenshots/screencapture/live demo)

2023-06-05 09:08 UTC, Firsttryy requested changes

2023-06-05 09:08 UTC, Firsttryy commented on app/lib/guidelines/Guidelines.js
> +        link: 'https://github.com/Noel-Bastubbe/for-Construction-Modeling/wiki/Dependency-Model#dep2---link-every-objectives-to-at-least-one-other-objective'
bitte durch
https://github.com/Noel-Bastubbe/for-Construction-Modeling/wiki/Dependency-Model#dep2---link-every-objective-to-at-least-one-other-objective
ersetzen (objectives zu objective geändert)

2023-06-05 09:09 UTC, Firsttryy commented on app/lib/guidelines/Guidelines.js
> +        link: 'https://github.com/Noel-Bastubbe/for-Construction-Modeling/wiki/Dependency-Model#dep2---link-every-objectives-to-at-least-one-other-objective'
```suggestion
        link: 'https://github.com/Noel-Bastubbe/for-Construction-Modeling/wiki/Dependency-Model#dep2---link-every-objective-to-at-least-one-other-objective'

```

2023-06-06 08:17 UTC, Noel-Bastubbe approved these changes

2023-06-06 08:19 UTC, Firsttryy approved these changes
lgtm

2023-06-06 08:20 UTC, merged